version: '2'

services:
  # this is our kafka cluster.
  lenses:
    image: landoop/kafka-lenses-dev
    environment:
      ADV_HOST: 127.0.0.1
      EULA: "https://dl.lenses.stream/d/?id=961a142c-dcf9-41de-9130-f393ef9af82b"
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3031:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker

